name: Run Daily Scraper

on:
  schedule:
    - cron: '41 5 * * *'  # runs daily at 8AM Thailand #cron: '35 5 * * *'  # Runs at 12:35 PM Thailand time '0 1 * * *'
  workflow_dispatch:     # allow manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run scraper
      run: |
        python main.py
